// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// VoiceSettingsColumns holds the columns for the "voice_settings" table.
	VoiceSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString, Unique: true},
		{Name: "voice_name", Type: field.TypeString, Nullable: true},
		{Name: "speaking_rate", Type: field.TypeFloat64, Nullable: true},
		{Name: "pitch", Type: field.TypeFloat64, Nullable: true},
	}
	// VoiceSettingsTable holds the schema information for the "voice_settings" table.
	VoiceSettingsTable = &schema.Table{
		Name:       "voice_settings",
		Columns:    VoiceSettingsColumns,
		PrimaryKey: []*schema.Column{VoiceSettingsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		VoiceSettingsTable,
	}
)

func init() {
}
