// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/kechako/yomiko/ent/schema"
	"github.com/kechako/yomiko/ent/voicesetting"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	voicesettingFields := schema.VoiceSetting{}.Fields()
	_ = voicesettingFields
	// voicesettingDescUserID is the schema descriptor for user_id field.
	voicesettingDescUserID := voicesettingFields[0].Descriptor()
	// voicesetting.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	voicesetting.UserIDValidator = voicesettingDescUserID.Validators[0].(func(string) error)
}
