// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kechako/yomiko/ent/voicesetting"
)

// VoiceSettingCreate is the builder for creating a VoiceSetting entity.
type VoiceSettingCreate struct {
	config
	mutation *VoiceSettingMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (vsc *VoiceSettingCreate) SetUserID(s string) *VoiceSettingCreate {
	vsc.mutation.SetUserID(s)
	return vsc
}

// SetVoiceName sets the "voice_name" field.
func (vsc *VoiceSettingCreate) SetVoiceName(s string) *VoiceSettingCreate {
	vsc.mutation.SetVoiceName(s)
	return vsc
}

// SetNillableVoiceName sets the "voice_name" field if the given value is not nil.
func (vsc *VoiceSettingCreate) SetNillableVoiceName(s *string) *VoiceSettingCreate {
	if s != nil {
		vsc.SetVoiceName(*s)
	}
	return vsc
}

// SetSpeakingRate sets the "speaking_rate" field.
func (vsc *VoiceSettingCreate) SetSpeakingRate(f float64) *VoiceSettingCreate {
	vsc.mutation.SetSpeakingRate(f)
	return vsc
}

// SetNillableSpeakingRate sets the "speaking_rate" field if the given value is not nil.
func (vsc *VoiceSettingCreate) SetNillableSpeakingRate(f *float64) *VoiceSettingCreate {
	if f != nil {
		vsc.SetSpeakingRate(*f)
	}
	return vsc
}

// SetPitch sets the "pitch" field.
func (vsc *VoiceSettingCreate) SetPitch(f float64) *VoiceSettingCreate {
	vsc.mutation.SetPitch(f)
	return vsc
}

// SetNillablePitch sets the "pitch" field if the given value is not nil.
func (vsc *VoiceSettingCreate) SetNillablePitch(f *float64) *VoiceSettingCreate {
	if f != nil {
		vsc.SetPitch(*f)
	}
	return vsc
}

// Mutation returns the VoiceSettingMutation object of the builder.
func (vsc *VoiceSettingCreate) Mutation() *VoiceSettingMutation {
	return vsc.mutation
}

// Save creates the VoiceSetting in the database.
func (vsc *VoiceSettingCreate) Save(ctx context.Context) (*VoiceSetting, error) {
	return withHooks(ctx, vsc.sqlSave, vsc.mutation, vsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (vsc *VoiceSettingCreate) SaveX(ctx context.Context) *VoiceSetting {
	v, err := vsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vsc *VoiceSettingCreate) Exec(ctx context.Context) error {
	_, err := vsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vsc *VoiceSettingCreate) ExecX(ctx context.Context) {
	if err := vsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vsc *VoiceSettingCreate) check() error {
	if _, ok := vsc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "VoiceSetting.user_id"`)}
	}
	if v, ok := vsc.mutation.UserID(); ok {
		if err := voicesetting.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "VoiceSetting.user_id": %w`, err)}
		}
	}
	return nil
}

func (vsc *VoiceSettingCreate) sqlSave(ctx context.Context) (*VoiceSetting, error) {
	if err := vsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := vsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, vsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	vsc.mutation.id = &_node.ID
	vsc.mutation.done = true
	return _node, nil
}

func (vsc *VoiceSettingCreate) createSpec() (*VoiceSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &VoiceSetting{config: vsc.config}
		_spec = sqlgraph.NewCreateSpec(voicesetting.Table, sqlgraph.NewFieldSpec(voicesetting.FieldID, field.TypeInt))
	)
	if value, ok := vsc.mutation.UserID(); ok {
		_spec.SetField(voicesetting.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := vsc.mutation.VoiceName(); ok {
		_spec.SetField(voicesetting.FieldVoiceName, field.TypeString, value)
		_node.VoiceName = &value
	}
	if value, ok := vsc.mutation.SpeakingRate(); ok {
		_spec.SetField(voicesetting.FieldSpeakingRate, field.TypeFloat64, value)
		_node.SpeakingRate = &value
	}
	if value, ok := vsc.mutation.Pitch(); ok {
		_spec.SetField(voicesetting.FieldPitch, field.TypeFloat64, value)
		_node.Pitch = &value
	}
	return _node, _spec
}

// VoiceSettingCreateBulk is the builder for creating many VoiceSetting entities in bulk.
type VoiceSettingCreateBulk struct {
	config
	err      error
	builders []*VoiceSettingCreate
}

// Save creates the VoiceSetting entities in the database.
func (vscb *VoiceSettingCreateBulk) Save(ctx context.Context) ([]*VoiceSetting, error) {
	if vscb.err != nil {
		return nil, vscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(vscb.builders))
	nodes := make([]*VoiceSetting, len(vscb.builders))
	mutators := make([]Mutator, len(vscb.builders))
	for i := range vscb.builders {
		func(i int, root context.Context) {
			builder := vscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VoiceSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, vscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, vscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, vscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (vscb *VoiceSettingCreateBulk) SaveX(ctx context.Context) []*VoiceSetting {
	v, err := vscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vscb *VoiceSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := vscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vscb *VoiceSettingCreateBulk) ExecX(ctx context.Context) {
	if err := vscb.Exec(ctx); err != nil {
		panic(err)
	}
}
