// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kechako/yomiko/ent/predicate"
	"github.com/kechako/yomiko/ent/voicesetting"
)

// VoiceSettingUpdate is the builder for updating VoiceSetting entities.
type VoiceSettingUpdate struct {
	config
	hooks    []Hook
	mutation *VoiceSettingMutation
}

// Where appends a list predicates to the VoiceSettingUpdate builder.
func (_u *VoiceSettingUpdate) Where(ps ...predicate.VoiceSetting) *VoiceSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVoiceName sets the "voice_name" field.
func (_u *VoiceSettingUpdate) SetVoiceName(v string) *VoiceSettingUpdate {
	_u.mutation.SetVoiceName(v)
	return _u
}

// SetNillableVoiceName sets the "voice_name" field if the given value is not nil.
func (_u *VoiceSettingUpdate) SetNillableVoiceName(v *string) *VoiceSettingUpdate {
	if v != nil {
		_u.SetVoiceName(*v)
	}
	return _u
}

// ClearVoiceName clears the value of the "voice_name" field.
func (_u *VoiceSettingUpdate) ClearVoiceName() *VoiceSettingUpdate {
	_u.mutation.ClearVoiceName()
	return _u
}

// SetSpeakingRate sets the "speaking_rate" field.
func (_u *VoiceSettingUpdate) SetSpeakingRate(v float64) *VoiceSettingUpdate {
	_u.mutation.ResetSpeakingRate()
	_u.mutation.SetSpeakingRate(v)
	return _u
}

// SetNillableSpeakingRate sets the "speaking_rate" field if the given value is not nil.
func (_u *VoiceSettingUpdate) SetNillableSpeakingRate(v *float64) *VoiceSettingUpdate {
	if v != nil {
		_u.SetSpeakingRate(*v)
	}
	return _u
}

// AddSpeakingRate adds value to the "speaking_rate" field.
func (_u *VoiceSettingUpdate) AddSpeakingRate(v float64) *VoiceSettingUpdate {
	_u.mutation.AddSpeakingRate(v)
	return _u
}

// ClearSpeakingRate clears the value of the "speaking_rate" field.
func (_u *VoiceSettingUpdate) ClearSpeakingRate() *VoiceSettingUpdate {
	_u.mutation.ClearSpeakingRate()
	return _u
}

// SetPitch sets the "pitch" field.
func (_u *VoiceSettingUpdate) SetPitch(v float64) *VoiceSettingUpdate {
	_u.mutation.ResetPitch()
	_u.mutation.SetPitch(v)
	return _u
}

// SetNillablePitch sets the "pitch" field if the given value is not nil.
func (_u *VoiceSettingUpdate) SetNillablePitch(v *float64) *VoiceSettingUpdate {
	if v != nil {
		_u.SetPitch(*v)
	}
	return _u
}

// AddPitch adds value to the "pitch" field.
func (_u *VoiceSettingUpdate) AddPitch(v float64) *VoiceSettingUpdate {
	_u.mutation.AddPitch(v)
	return _u
}

// ClearPitch clears the value of the "pitch" field.
func (_u *VoiceSettingUpdate) ClearPitch() *VoiceSettingUpdate {
	_u.mutation.ClearPitch()
	return _u
}

// Mutation returns the VoiceSettingMutation object of the builder.
func (_u *VoiceSettingUpdate) Mutation() *VoiceSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VoiceSettingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VoiceSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VoiceSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VoiceSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *VoiceSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(voicesetting.Table, voicesetting.Columns, sqlgraph.NewFieldSpec(voicesetting.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.VoiceName(); ok {
		_spec.SetField(voicesetting.FieldVoiceName, field.TypeString, value)
	}
	if _u.mutation.VoiceNameCleared() {
		_spec.ClearField(voicesetting.FieldVoiceName, field.TypeString)
	}
	if value, ok := _u.mutation.SpeakingRate(); ok {
		_spec.SetField(voicesetting.FieldSpeakingRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSpeakingRate(); ok {
		_spec.AddField(voicesetting.FieldSpeakingRate, field.TypeFloat64, value)
	}
	if _u.mutation.SpeakingRateCleared() {
		_spec.ClearField(voicesetting.FieldSpeakingRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Pitch(); ok {
		_spec.SetField(voicesetting.FieldPitch, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPitch(); ok {
		_spec.AddField(voicesetting.FieldPitch, field.TypeFloat64, value)
	}
	if _u.mutation.PitchCleared() {
		_spec.ClearField(voicesetting.FieldPitch, field.TypeFloat64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{voicesetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VoiceSettingUpdateOne is the builder for updating a single VoiceSetting entity.
type VoiceSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VoiceSettingMutation
}

// SetVoiceName sets the "voice_name" field.
func (_u *VoiceSettingUpdateOne) SetVoiceName(v string) *VoiceSettingUpdateOne {
	_u.mutation.SetVoiceName(v)
	return _u
}

// SetNillableVoiceName sets the "voice_name" field if the given value is not nil.
func (_u *VoiceSettingUpdateOne) SetNillableVoiceName(v *string) *VoiceSettingUpdateOne {
	if v != nil {
		_u.SetVoiceName(*v)
	}
	return _u
}

// ClearVoiceName clears the value of the "voice_name" field.
func (_u *VoiceSettingUpdateOne) ClearVoiceName() *VoiceSettingUpdateOne {
	_u.mutation.ClearVoiceName()
	return _u
}

// SetSpeakingRate sets the "speaking_rate" field.
func (_u *VoiceSettingUpdateOne) SetSpeakingRate(v float64) *VoiceSettingUpdateOne {
	_u.mutation.ResetSpeakingRate()
	_u.mutation.SetSpeakingRate(v)
	return _u
}

// SetNillableSpeakingRate sets the "speaking_rate" field if the given value is not nil.
func (_u *VoiceSettingUpdateOne) SetNillableSpeakingRate(v *float64) *VoiceSettingUpdateOne {
	if v != nil {
		_u.SetSpeakingRate(*v)
	}
	return _u
}

// AddSpeakingRate adds value to the "speaking_rate" field.
func (_u *VoiceSettingUpdateOne) AddSpeakingRate(v float64) *VoiceSettingUpdateOne {
	_u.mutation.AddSpeakingRate(v)
	return _u
}

// ClearSpeakingRate clears the value of the "speaking_rate" field.
func (_u *VoiceSettingUpdateOne) ClearSpeakingRate() *VoiceSettingUpdateOne {
	_u.mutation.ClearSpeakingRate()
	return _u
}

// SetPitch sets the "pitch" field.
func (_u *VoiceSettingUpdateOne) SetPitch(v float64) *VoiceSettingUpdateOne {
	_u.mutation.ResetPitch()
	_u.mutation.SetPitch(v)
	return _u
}

// SetNillablePitch sets the "pitch" field if the given value is not nil.
func (_u *VoiceSettingUpdateOne) SetNillablePitch(v *float64) *VoiceSettingUpdateOne {
	if v != nil {
		_u.SetPitch(*v)
	}
	return _u
}

// AddPitch adds value to the "pitch" field.
func (_u *VoiceSettingUpdateOne) AddPitch(v float64) *VoiceSettingUpdateOne {
	_u.mutation.AddPitch(v)
	return _u
}

// ClearPitch clears the value of the "pitch" field.
func (_u *VoiceSettingUpdateOne) ClearPitch() *VoiceSettingUpdateOne {
	_u.mutation.ClearPitch()
	return _u
}

// Mutation returns the VoiceSettingMutation object of the builder.
func (_u *VoiceSettingUpdateOne) Mutation() *VoiceSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the VoiceSettingUpdate builder.
func (_u *VoiceSettingUpdateOne) Where(ps ...predicate.VoiceSetting) *VoiceSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VoiceSettingUpdateOne) Select(field string, fields ...string) *VoiceSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VoiceSetting entity.
func (_u *VoiceSettingUpdateOne) Save(ctx context.Context) (*VoiceSetting, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VoiceSettingUpdateOne) SaveX(ctx context.Context) *VoiceSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VoiceSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VoiceSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *VoiceSettingUpdateOne) sqlSave(ctx context.Context) (_node *VoiceSetting, err error) {
	_spec := sqlgraph.NewUpdateSpec(voicesetting.Table, voicesetting.Columns, sqlgraph.NewFieldSpec(voicesetting.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VoiceSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, voicesetting.FieldID)
		for _, f := range fields {
			if !voicesetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != voicesetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.VoiceName(); ok {
		_spec.SetField(voicesetting.FieldVoiceName, field.TypeString, value)
	}
	if _u.mutation.VoiceNameCleared() {
		_spec.ClearField(voicesetting.FieldVoiceName, field.TypeString)
	}
	if value, ok := _u.mutation.SpeakingRate(); ok {
		_spec.SetField(voicesetting.FieldSpeakingRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSpeakingRate(); ok {
		_spec.AddField(voicesetting.FieldSpeakingRate, field.TypeFloat64, value)
	}
	if _u.mutation.SpeakingRateCleared() {
		_spec.ClearField(voicesetting.FieldSpeakingRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Pitch(); ok {
		_spec.SetField(voicesetting.FieldPitch, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPitch(); ok {
		_spec.AddField(voicesetting.FieldPitch, field.TypeFloat64, value)
	}
	if _u.mutation.PitchCleared() {
		_spec.ClearField(voicesetting.FieldPitch, field.TypeFloat64)
	}
	_node = &VoiceSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{voicesetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
