// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kechako/yomiko/ent/predicate"
	"github.com/kechako/yomiko/ent/voicesetting"
)

// VoiceSettingQuery is the builder for querying VoiceSetting entities.
type VoiceSettingQuery struct {
	config
	ctx        *QueryContext
	order      []voicesetting.OrderOption
	inters     []Interceptor
	predicates []predicate.VoiceSetting
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VoiceSettingQuery builder.
func (vsq *VoiceSettingQuery) Where(ps ...predicate.VoiceSetting) *VoiceSettingQuery {
	vsq.predicates = append(vsq.predicates, ps...)
	return vsq
}

// Limit the number of records to be returned by this query.
func (vsq *VoiceSettingQuery) Limit(limit int) *VoiceSettingQuery {
	vsq.ctx.Limit = &limit
	return vsq
}

// Offset to start from.
func (vsq *VoiceSettingQuery) Offset(offset int) *VoiceSettingQuery {
	vsq.ctx.Offset = &offset
	return vsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vsq *VoiceSettingQuery) Unique(unique bool) *VoiceSettingQuery {
	vsq.ctx.Unique = &unique
	return vsq
}

// Order specifies how the records should be ordered.
func (vsq *VoiceSettingQuery) Order(o ...voicesetting.OrderOption) *VoiceSettingQuery {
	vsq.order = append(vsq.order, o...)
	return vsq
}

// First returns the first VoiceSetting entity from the query.
// Returns a *NotFoundError when no VoiceSetting was found.
func (vsq *VoiceSettingQuery) First(ctx context.Context) (*VoiceSetting, error) {
	nodes, err := vsq.Limit(1).All(setContextOp(ctx, vsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{voicesetting.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vsq *VoiceSettingQuery) FirstX(ctx context.Context) *VoiceSetting {
	node, err := vsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VoiceSetting ID from the query.
// Returns a *NotFoundError when no VoiceSetting ID was found.
func (vsq *VoiceSettingQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vsq.Limit(1).IDs(setContextOp(ctx, vsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{voicesetting.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vsq *VoiceSettingQuery) FirstIDX(ctx context.Context) int {
	id, err := vsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VoiceSetting entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VoiceSetting entity is found.
// Returns a *NotFoundError when no VoiceSetting entities are found.
func (vsq *VoiceSettingQuery) Only(ctx context.Context) (*VoiceSetting, error) {
	nodes, err := vsq.Limit(2).All(setContextOp(ctx, vsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{voicesetting.Label}
	default:
		return nil, &NotSingularError{voicesetting.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vsq *VoiceSettingQuery) OnlyX(ctx context.Context) *VoiceSetting {
	node, err := vsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VoiceSetting ID in the query.
// Returns a *NotSingularError when more than one VoiceSetting ID is found.
// Returns a *NotFoundError when no entities are found.
func (vsq *VoiceSettingQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vsq.Limit(2).IDs(setContextOp(ctx, vsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{voicesetting.Label}
	default:
		err = &NotSingularError{voicesetting.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vsq *VoiceSettingQuery) OnlyIDX(ctx context.Context) int {
	id, err := vsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VoiceSettings.
func (vsq *VoiceSettingQuery) All(ctx context.Context) ([]*VoiceSetting, error) {
	ctx = setContextOp(ctx, vsq.ctx, "All")
	if err := vsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VoiceSetting, *VoiceSettingQuery]()
	return withInterceptors[[]*VoiceSetting](ctx, vsq, qr, vsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (vsq *VoiceSettingQuery) AllX(ctx context.Context) []*VoiceSetting {
	nodes, err := vsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VoiceSetting IDs.
func (vsq *VoiceSettingQuery) IDs(ctx context.Context) (ids []int, err error) {
	if vsq.ctx.Unique == nil && vsq.path != nil {
		vsq.Unique(true)
	}
	ctx = setContextOp(ctx, vsq.ctx, "IDs")
	if err = vsq.Select(voicesetting.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vsq *VoiceSettingQuery) IDsX(ctx context.Context) []int {
	ids, err := vsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vsq *VoiceSettingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, vsq.ctx, "Count")
	if err := vsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, vsq, querierCount[*VoiceSettingQuery](), vsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (vsq *VoiceSettingQuery) CountX(ctx context.Context) int {
	count, err := vsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vsq *VoiceSettingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, vsq.ctx, "Exist")
	switch _, err := vsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (vsq *VoiceSettingQuery) ExistX(ctx context.Context) bool {
	exist, err := vsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VoiceSettingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vsq *VoiceSettingQuery) Clone() *VoiceSettingQuery {
	if vsq == nil {
		return nil
	}
	return &VoiceSettingQuery{
		config:     vsq.config,
		ctx:        vsq.ctx.Clone(),
		order:      append([]voicesetting.OrderOption{}, vsq.order...),
		inters:     append([]Interceptor{}, vsq.inters...),
		predicates: append([]predicate.VoiceSetting{}, vsq.predicates...),
		// clone intermediate query.
		sql:  vsq.sql.Clone(),
		path: vsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VoiceSetting.Query().
//		GroupBy(voicesetting.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vsq *VoiceSettingQuery) GroupBy(field string, fields ...string) *VoiceSettingGroupBy {
	vsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VoiceSettingGroupBy{build: vsq}
	grbuild.flds = &vsq.ctx.Fields
	grbuild.label = voicesetting.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID string `json:"user_id,omitempty"`
//	}
//
//	client.VoiceSetting.Query().
//		Select(voicesetting.FieldUserID).
//		Scan(ctx, &v)
func (vsq *VoiceSettingQuery) Select(fields ...string) *VoiceSettingSelect {
	vsq.ctx.Fields = append(vsq.ctx.Fields, fields...)
	sbuild := &VoiceSettingSelect{VoiceSettingQuery: vsq}
	sbuild.label = voicesetting.Label
	sbuild.flds, sbuild.scan = &vsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VoiceSettingSelect configured with the given aggregations.
func (vsq *VoiceSettingQuery) Aggregate(fns ...AggregateFunc) *VoiceSettingSelect {
	return vsq.Select().Aggregate(fns...)
}

func (vsq *VoiceSettingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range vsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, vsq); err != nil {
				return err
			}
		}
	}
	for _, f := range vsq.ctx.Fields {
		if !voicesetting.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vsq.path != nil {
		prev, err := vsq.path(ctx)
		if err != nil {
			return err
		}
		vsq.sql = prev
	}
	return nil
}

func (vsq *VoiceSettingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VoiceSetting, error) {
	var (
		nodes = []*VoiceSetting{}
		_spec = vsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VoiceSetting).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VoiceSetting{config: vsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (vsq *VoiceSettingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vsq.querySpec()
	_spec.Node.Columns = vsq.ctx.Fields
	if len(vsq.ctx.Fields) > 0 {
		_spec.Unique = vsq.ctx.Unique != nil && *vsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, vsq.driver, _spec)
}

func (vsq *VoiceSettingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(voicesetting.Table, voicesetting.Columns, sqlgraph.NewFieldSpec(voicesetting.FieldID, field.TypeInt))
	_spec.From = vsq.sql
	if unique := vsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if vsq.path != nil {
		_spec.Unique = true
	}
	if fields := vsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, voicesetting.FieldID)
		for i := range fields {
			if fields[i] != voicesetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vsq *VoiceSettingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vsq.driver.Dialect())
	t1 := builder.Table(voicesetting.Table)
	columns := vsq.ctx.Fields
	if len(columns) == 0 {
		columns = voicesetting.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vsq.sql != nil {
		selector = vsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vsq.ctx.Unique != nil && *vsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range vsq.predicates {
		p(selector)
	}
	for _, p := range vsq.order {
		p(selector)
	}
	if offset := vsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VoiceSettingGroupBy is the group-by builder for VoiceSetting entities.
type VoiceSettingGroupBy struct {
	selector
	build *VoiceSettingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vsgb *VoiceSettingGroupBy) Aggregate(fns ...AggregateFunc) *VoiceSettingGroupBy {
	vsgb.fns = append(vsgb.fns, fns...)
	return vsgb
}

// Scan applies the selector query and scans the result into the given value.
func (vsgb *VoiceSettingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vsgb.build.ctx, "GroupBy")
	if err := vsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VoiceSettingQuery, *VoiceSettingGroupBy](ctx, vsgb.build, vsgb, vsgb.build.inters, v)
}

func (vsgb *VoiceSettingGroupBy) sqlScan(ctx context.Context, root *VoiceSettingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vsgb.fns))
	for _, fn := range vsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vsgb.flds)+len(vsgb.fns))
		for _, f := range *vsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VoiceSettingSelect is the builder for selecting fields of VoiceSetting entities.
type VoiceSettingSelect struct {
	*VoiceSettingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vss *VoiceSettingSelect) Aggregate(fns ...AggregateFunc) *VoiceSettingSelect {
	vss.fns = append(vss.fns, fns...)
	return vss
}

// Scan applies the selector query and scans the result into the given value.
func (vss *VoiceSettingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vss.ctx, "Select")
	if err := vss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VoiceSettingQuery, *VoiceSettingSelect](ctx, vss.VoiceSettingQuery, vss, vss.inters, v)
}

func (vss *VoiceSettingSelect) sqlScan(ctx context.Context, root *VoiceSettingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vss.fns))
	for _, fn := range vss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
