// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kechako/yomiko/ent/voicesetting"
)

// VoiceSettingCreate is the builder for creating a VoiceSetting entity.
type VoiceSettingCreate struct {
	config
	mutation *VoiceSettingMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *VoiceSettingCreate) SetUserID(v string) *VoiceSettingCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetVoiceName sets the "voice_name" field.
func (_c *VoiceSettingCreate) SetVoiceName(v string) *VoiceSettingCreate {
	_c.mutation.SetVoiceName(v)
	return _c
}

// SetNillableVoiceName sets the "voice_name" field if the given value is not nil.
func (_c *VoiceSettingCreate) SetNillableVoiceName(v *string) *VoiceSettingCreate {
	if v != nil {
		_c.SetVoiceName(*v)
	}
	return _c
}

// SetSpeakingRate sets the "speaking_rate" field.
func (_c *VoiceSettingCreate) SetSpeakingRate(v float64) *VoiceSettingCreate {
	_c.mutation.SetSpeakingRate(v)
	return _c
}

// SetNillableSpeakingRate sets the "speaking_rate" field if the given value is not nil.
func (_c *VoiceSettingCreate) SetNillableSpeakingRate(v *float64) *VoiceSettingCreate {
	if v != nil {
		_c.SetSpeakingRate(*v)
	}
	return _c
}

// SetPitch sets the "pitch" field.
func (_c *VoiceSettingCreate) SetPitch(v float64) *VoiceSettingCreate {
	_c.mutation.SetPitch(v)
	return _c
}

// SetNillablePitch sets the "pitch" field if the given value is not nil.
func (_c *VoiceSettingCreate) SetNillablePitch(v *float64) *VoiceSettingCreate {
	if v != nil {
		_c.SetPitch(*v)
	}
	return _c
}

// Mutation returns the VoiceSettingMutation object of the builder.
func (_c *VoiceSettingCreate) Mutation() *VoiceSettingMutation {
	return _c.mutation
}

// Save creates the VoiceSetting in the database.
func (_c *VoiceSettingCreate) Save(ctx context.Context) (*VoiceSetting, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VoiceSettingCreate) SaveX(ctx context.Context) *VoiceSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VoiceSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VoiceSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VoiceSettingCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "VoiceSetting.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := voicesetting.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "VoiceSetting.user_id": %w`, err)}
		}
	}
	return nil
}

func (_c *VoiceSettingCreate) sqlSave(ctx context.Context) (*VoiceSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VoiceSettingCreate) createSpec() (*VoiceSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &VoiceSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(voicesetting.Table, sqlgraph.NewFieldSpec(voicesetting.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(voicesetting.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.VoiceName(); ok {
		_spec.SetField(voicesetting.FieldVoiceName, field.TypeString, value)
		_node.VoiceName = &value
	}
	if value, ok := _c.mutation.SpeakingRate(); ok {
		_spec.SetField(voicesetting.FieldSpeakingRate, field.TypeFloat64, value)
		_node.SpeakingRate = &value
	}
	if value, ok := _c.mutation.Pitch(); ok {
		_spec.SetField(voicesetting.FieldPitch, field.TypeFloat64, value)
		_node.Pitch = &value
	}
	return _node, _spec
}

// VoiceSettingCreateBulk is the builder for creating many VoiceSetting entities in bulk.
type VoiceSettingCreateBulk struct {
	config
	err      error
	builders []*VoiceSettingCreate
}

// Save creates the VoiceSetting entities in the database.
func (_c *VoiceSettingCreateBulk) Save(ctx context.Context) ([]*VoiceSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VoiceSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VoiceSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VoiceSettingCreateBulk) SaveX(ctx context.Context) []*VoiceSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VoiceSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VoiceSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
