// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// VoiceSetting is the predicate function for voicesetting builders.
type VoiceSetting func(*sql.Selector)
